install.packages("devtools")
library("devtools")
install_version("yaml", version = "2.2.0", repos = " https://CRAN.R-project.org")
install_version("learnr", version = "0.9.2.1", repos = " https://CRAN.R-project.org")
install_version("RCurl", version = "1.95.4.12", repos = " https://CRAN.R-project.org")
install_version("formatR", version = "1.6", repos = " https://CRAN.R-project.org")
install_version("caTools", version = "1.17.1.2", repos = " https://CRAN.R-project.org")
install_version("ggplot2", version = "3.1.1", repos = " https://CRAN.R-project.org")
install_version("datasets", version = "3.5.2", repos = " https://CRAN.R-project.org")