---
title: "Invasive Species and Infection"
author: "Amy Kendig"
date: "3/8/2019"
output:
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## What is an invasive species?

We talked a little bit about invasive species at the field site, but let's discuss them more.
Has anyone heard of kudzu, Burmese pythons, or lionfish?  

* Props: pictures of each

Tell me a little about what you know about these species

* Kudzu grows over buildings and other plants, which causes structural damage and suppresses native species  
* Burmese pythons consume animals like deer, racoons, rabbits, and other mammals, which not only affect those populations, but top predators like panthers and alligators. They also consume birds, inclduing endangered species.  
* Lionfish consume other fish, which could have large effects on fisheries and the biodiversity of coral reefs.

What do these species have in common?

* Negatively affect native species
* Categorized as "invasive"
* They are all found in Florida
* Prop: Have distributions from EDDMaps available to show 

What causes a species to be called "invasive"?

* Usually, they are not native, meaning that they were probably introduced accidentally or on purpose by humans
* They have relatively large population sizes
* They have a negative impact on humans and/or species that we care about (e.g. native or agricultural)

With a partner, come up with answers to these two questions:

* What are some negative impacts of invasive species that you might care about?
* How is it possible that invasive species can get to this point where they have large populations and are destructive?

Review answers, some possibilities:

* Impacts: reduced native plant diversity, fewer mammals, fewer birds, make species endangered, make buildings or land less valuable
* Success: fewer predators/herbivores/diseases or better tolerance, better competitors than native species, use a unique set of resources for that location, can take advantage of mutualisms better than native species 

Emphasize that plants get diseases, just like people, and that these can affect survival and reproduction.

## Activity explanation

Today, we're going to collect data from an experiment that has the overall goal of understanding how an invasive species affects disease spread. In the greenhouse we grew a widespread invasive species, *Microstegium vimineum*, and a native species, *Elymus virginicus*. We sprayed half of thes with fungicide, which suppresses the growth of fungal pathogens.  

What is a fungus and what is a pathogen?

* A fungus is an organism that produces spores. You might be familiar with mushrooms or yeast, which are fungi.
* A pathogen feeds off a host in order to survive and usually hurts the host

We are using fungicide to suppress a fungal pathogen like the one on these plants (show example infected *M. vimineum* plants) in a field experiment in Indiana. However, we don't know if there are any side effects of the fungicide. So these plants are meant to answer that question.

What are some traits of these plants we could measure to try to understand if fungicide affects growth?

In your notebook, label each line with these (prop - poster with these):

* Pot (for pot number/ID)
* Species
* Fungicide
* Height
* Leaf weight
* Leaf area

You will record the data for two pots - one with the invasive species and one with the native species.

In your notebook, write down your hypothesis:

* How does fungicide affece the growth of the invasive species and the native species?

Share some of your hypotheses.

To measure height, we have tape measures next to the pots. Choose the longest part of the plant to measure from the soil up to the top. To measure leaf weight, chose one leaf and measure it with the scale. Then, bring that leaf over to the scanner. We'll use this to tell you leaf area. Once you have picked a pot, move it to this other table so that it doesn't get measured twice. 

Can someone explain to use how to use the scale?

* zero it
* use the weigh boat
* wait for it to stabilize

## Supplies

Props:

* Invasive species pictures and EDDMapS distribution
* Data collection poster

Materials:

* Notebooks
* Pencils
* Measuring tape
* Scale
* Weigh boat
* Scanner
* Computer